example_type_data:
  -
    name: basic
    generator_options: ""
  -
    name: basic-server-rendering
    generator_options: --server-rendering
  -
    name: redux
    generator_options: --redux --server-rendering
  -
    name: redux-server-rendering
    generator_options: --redux --server-rendering
  -
    name: heroku-deployment
    generator_options: --heroku-deployment
