# Used by webpacker_lite to configure the helpers and by webpack from the
# client/webpack.client.base.config.js and other sibling config files, using variable `paths`.
default: &default
  output: public
  manifest: manifest.json

development:
  <<: *default
  assets: webpack/development

test:
  <<: *default
  assets: webpack/test

production:
  <<: *default
  assets: webpack/production
